server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/micro_db?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234567
    platform: mysql
    schema: classpath:schema.sql
    data: classpath:data.sql
  jpa:
    generate-ddl: false
    show-sql: true
  application:
    name: microservice-provider-user
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/